name: adaptive-optimal
port: 10000
secretWord: Foobar
timeoutMinutes: 10
timeoutMinBlocks: 4
instructionlevel: adaptive
weightTrainingDatabase: "jdbc:mariadb://localhost:3306/MINECRAFTTEST"
weightSource: optimal
trainingNumBootstrapRuns: 100
