name: blocklevel-optimal
port: 10000
secretWord: Foobar
timeoutMinutes: 10
timeoutMinBlocks: 4
instructionlevel: BLOCK
weightTrainingDatabase: "jdbc:mariadb://localhost:3306/MINECRAFTTEST"
weightSource: optimal
weightTrainingArchitectName: "%-optimal"
trainingNumBootstrapRuns: 100
